#pragma once

#include <stdint.h>

#define ESP_BMS_BMS_SAFETY_CELL_OV (UINT16_C(1) << 0)
#define ESP_BMS_BMS_SAFETY_CELL_UV (UINT16_C(1) << 1)
#define ESP_BMS_BMS_SAFETY_OVER_TEMP (UINT16_C(1) << 2)
#define ESP_BMS_BMS_SAFETY_UNDER_TEMP (UINT16_C(1) << 3)
#define ESP_BMS_BMS_SAFETY_OVER_CURRENT (UINT16_C(1) << 4)
#define ESP_BMS_BMS_SAFETY_SHORT_CIRCUIT (UINT16_C(1) << 5)
#define ESP_BMS_BMS_SAFETY_CELL_DELTA (UINT16_C(1) << 6)
#define ESP_BMS_BMS_SAFETY_BALANCING (UINT16_C(1) << 7)
#define ESP_BMS_BMS_SAFETY_COUNT 8U
#define ESP_BMS_BMS_SAFETY_KNOWN_MASK                                                   \
    (ESP_BMS_BMS_SAFETY_CELL_OV | ESP_BMS_BMS_SAFETY_CELL_UV |                          \
     ESP_BMS_BMS_SAFETY_OVER_TEMP | ESP_BMS_BMS_SAFETY_UNDER_TEMP |                     \
     ESP_BMS_BMS_SAFETY_OVER_CURRENT | ESP_BMS_BMS_SAFETY_SHORT_CIRCUIT |               \
     ESP_BMS_BMS_SAFETY_CELL_DELTA | ESP_BMS_BMS_SAFETY_BALANCING)
